// Generated from FontMap.dat and extra_fontmap.ini. Do not edit by hand.

pub(crate) const CLASSES: &[(&str, &[&str])] = &[
    ("TIMES", &["Times New Roman", "TF Roman", "Times", "Lucida Bright", "TimesRoman"]),
    ("ARIAL", &["Arial", "TF Gothic", "Verdana", "Lucida Sans", "Helvetica"]),
    ("COURIER", &["Courier New", "Lucida Sans Typewriter", "Courier"]),
    ("HEADLINE", &["HY헤드라인M", "HY동녘M", "백묵 헤드라인"]),
    ("BATANG", &["Batang", "바탕", "BatangChe", "바탕체", "AppleMyungjo", "Baekmuk Batang", "백묵 바탕", "Myeongjo", "Haansoft Batang", "한컴바탕", "HCR Batang", "함초롬바탕", "FZSong_SuperFont", "한컴바탕확장"]),
    ("GULIM", &["Gulim", "굴림", "GulimChe", "굴림체", "AppleGothic", "Baekmuk Gulim", "백묵 굴림", "RoundedGothic", "Haansoft Dotum", "한컴 돋움", "Haansoft Batang", "한컴바탕", "HCR Dotum", "함초롬돋움"]),
    ("DOTUM", &["Dotum", "돋움", "DotumChe", "돋움체", "AppleGothic", "Baekmuk Dotum", "백묵 돋움", "Gothic", "Haansoft Dotum", "한컴 돋움", "Haansoft Batang", "한컴바탕", "Hancom Gothic", "한컴 고딕", "Han Santteut Dotum", "한컴산뜻돋움", "HCR Dotum", "함초롬돋움"]),
    ("GUNGSUH", &["Gungsuh", "궁서", "GungsuhChe", "궁서체", "AppleMyungjo", "Haeseo", "Haansoft Batang", "한컴바탕", "FZSong_SuperFont", "한컴바탕확장"]),
    ("MINCHO", &["MS Mincho", "ＭＳ 明朝", "MS PMincho", "ＭＳ Ｐ明朝", "Hiragino Mincho Pro W3", "Hiragino Mincho Pro", "Kochi Mincho", "東風明朝"]),
    ("GOTHIC", &["MS Gothic", "ＭＳ ゴシック", "MS PGothic", "ＭＳ Ｐゴシック", "Osaka", "Kochi Gothic", "東風ゴシック"]),
    ("SIMSUN", &["SimSun", "宋体", "Hei", "ZYSong18030", "中易宋体18030", "AR PL SungtiL GB", "文鼎ＰＬ简报宋"]),
    ("MINGLIU", &["PMingLiU", "新細明體", "MingLiU", "細明體", "DFKai-SB", "標楷體", "Apple LiGothic", "AR PL Mingti2L Big5", "文鼎ＰＬ細上海宋"]),
];

pub(crate) const MAP_FONT: &[(&str, &[&str])] = &[
    ("Juice ITC", &["Agency FB", "ahn2006-L", "Times New Roman", "HCR Batang"]),
    ("London", &["Old English Text MT"]),
    ("Los Angeles", &["Onyx"]),
    ("Gothic", &["Century Gothic"]),
    ("MT Symbol", &["Symbol"]),
    ("Arial Cyr", &["Bastion"]),
    ("Courier New Cyr", &["APC Courier"]),
    ("Times New Roman Cyr", &["Latinski"]),
    ("Kafisma Cyr", &["Latinski"]),
    ("Sistemny", &["Arial Black"]),
    ("Kristen ITC", &["한컴 윤체 M"]),
    ("HY견고딕", &["한양견고딕", "견고딕", "HY강B"]),
    ("HY견명조", &["한양견명조", "견명조"]),
    ("HY궁서", &["HY궁서", "한양궁서", "궁서"]),
    ("HY궁서B", &["HY궁서", "한양궁서", "궁서"]),
    ("HY그래픽", &["HY그래픽", "HY나무L", "그래픽"]),
    ("HY그래픽M", &["HY그래픽", "HY나무L", "그래픽"]),
    ("HY목판L", &["HY산B"]),
    ("HY백송B", &["HY동녘M"]),
    ("HY센스L", &["HY나무L"]),
    ("HY신명조", &["HY신명조", "한양신명조", "신명조"]),
    ("HY얕은샘물M", &["HY바다L"]),
    ("HY엽서L", &["HY나무M", "HY바다L"]),
    ("HY엽서M", &["HY나무B", "HY바다L"]),
    ("HY중고딕", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("HY크리스탈M", &["HY크리스탈M"]),
    ("HY목각파임B", &["HY산B"]),
    ("MD개성체", &["HY동녘M"]),
    ("MD솔체", &["HY동녘M"]),
    ("MD아롱체", &["HY동녘M"]),
    ("MD아트체", &["HY동녘M"]),
    ("MD이솝체", &["HY동녘M"]),
    ("견고딕", &["HY견고딕", "한양견고딕", "견고딕"]),
    ("견명조", &["HY견명조", "한양견명조", "견명조"]),
    ("그래픽", &["HY그래픽", "한양그래픽", "그래픽"]),
    ("신명조", &["HY신명조", "한양신명조", "신명조"]),
    ("신명조 간자", &["HY신명조", "한양신명조", "신명조"]),
    ("신명조 약자", &["HY신명조", "한양신명조", "신명조"]),
    ("신명조V", &["한양신명조V"]),
    ("신명조V", &["HY신명조", "한양신명조", "신명조"]),
    ("중고딕V", &["한양중고딕V"]),
    ("중고딕V", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("양재 다운명조M", &["HY신명조", "한양신명조", "신명조"]),
    ("중고딕", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("중고딕 간자", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("중고딕 약자", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("휴먼매직체", &["HY동녘M"]),
    ("휴먼엑스포", &["Arial Black"]),
    ("휴먼모음T", &["한컴 윤체 L"]),
    ("휴먼편지체", &["HY바다L"]),
    ("휴먼아미체", &["HY바다L"]),
    ("08서울남산체 L", &["한컴 윤고딕 230"]),
    ("08서울남산체 B", &["한컴 윤고딕 240"]),
    ("08서울남산체 EB", &["한컴 윤고딕 250"]),
    ("한양신명조", &["HY신명조", "한양신명조", "신명조"]),
    ("한양견명조", &["HY견명조", "한양견명조", "견명조"]),
    ("한양중고딕", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("한양견고딕", &["HY견고딕", "한양견고딕", "견고딕"]),
    ("한양그래픽", &["HY그래픽", "한양그래픽", "그래픽"]),
    ("한양궁서", &["HY궁서", "한양궁서", "궁서"]),
    ("한양신명조V", &["신명조V"]),
    ("한양신명조V", &["HY신명조", "한양신명조", "신명조"]),
    ("한양중고딕V", &["중고딕V"]),
    ("한양중고딕V", &["HY중고딕", "한양중고딕", "중고딕"]),
    ("소망L", &["HY바다L"]),
    ("가시나무M", &["HY산B"]),
    ("MS Mincho", &["Mincho", "平成明朝"]),
    ("平成明朝", &["リュウミンライト-ＫＬ", "本明朝−Ｍ", "細明朝体"]),
    ("本明朝−Ｍ", &["平成明朝"]),
    ("AR Pペン行楷書体L", &["平成明朝"]),
    ("AR Pペン楷書体L", &["平成明朝"]),
    ("ARペン行楷書体L", &["平成明朝"]),
    ("ARペン楷書体L", &["平成明朝"]),
    ("AR P勘亭流H", &["平成角ゴシック"]),
    ("AR P古印体B", &["平成角ゴシック"]),
    ("AR勘亭流H", &["平成角ゴシック"]),
    ("AR古印体B", &["平成角ゴシック"]),
    ("AR P行楷書体H", &["平成明朝"]),
    ("AR P行楷書体L", &["平成明朝"]),
    ("AR行楷連綿体H", &["平成明朝"]),
    ("AR行楷連綿体L", &["平成明朝"]),
    ("AR行楷書体H", &["平成明朝"]),
    ("AR行楷書体L", &["平成明朝"]),
    ("AR P隷書体M", &["平成角ゴシック"]),
    ("AR P楷書体M", &["平成明朝"]),
    ("AR隷書体M", &["平成角ゴシック"]),
    ("AR楷書体M", &["平成明朝"]),
    ("AR P黒丸ＰＯＰ体H", &["丸ゴシック−Ｍ"]),
    ("AR P白丸ＰＯＰ体H", &["丸ゴシック−Ｍ"]),
    ("AR黒丸ＰＯＰ体H", &["丸ゴシック−Ｍ"]),
    ("AR白丸ＰＯＰ体H", &["丸ゴシック−Ｍ"]),
    ("ＤＦPOP体", &["中ゴシックＢＢＢ"]),
    ("ＤＦＰPOP体", &["中ゴシックＢＢＢ"]),
    ("ＤＦＰ特太ゴシック体", &["中ゴシックＢＢＢ"]),
    ("ＤＦ特太ゴシック体", &["中ゴシックＢＢＢ"]),
    ("HGPｺﾞｼｯｸE", &["平成角ゴシック"]),
    ("HGPｺﾞｼｯｸM", &["平成角ゴシック"]),
    ("HGSｺﾞｼｯｸE", &["平成角ゴシック"]),
    ("HGSｺﾞｼｯｸM", &["平成角ゴシック"]),
    ("HGｺﾞｼｯｸE", &["平成角ゴシック"]),
    ("ＨＧｺﾞｼｯｸE-PRO", &["平成角ゴシック"]),
    ("HGｺﾞｼｯｸM", &["平成角ゴシック"]),
    ("HGP行書体", &["平成明朝"]),
    ("HGS行書体", &["平成明朝"]),
    ("HG行書体", &["平成明朝"]),
    ("HGP創英角ｺﾞｼｯｸUB", &["中ゴシックＢＢＢ"]),
    ("HGP創英角ﾎﾟｯﾌﾟ体", &["中ゴシックＢＢＢ"]),
    ("HGS創英角ｺﾞｼｯｸUB", &["中ゴシックＢＢＢ"]),
    ("HGS創英角ﾎﾟｯﾌﾟ体", &["中ゴシックＢＢＢ"]),
    ("HG創英角ｺﾞｼｯｸUB", &["中ゴシックＢＢＢ"]),
    ("HG創英角ﾎﾟｯﾌﾟ体", &["中ゴシックＢＢＢ"]),
    ("HGP明朝B", &["平成明朝"]),
    ("HGP明朝E", &["平成明朝"]),
    ("HGS明朝B", &["平成明朝"]),
    ("HGS明朝E", &["平成明朝"]),
    ("HG明朝B", &["平成明朝"]),
    ("HG明朝E", &["平成明朝"]),
    ("HG丸ｺﾞｼｯｸM-PRO", &["平成角ゴシック"]),
    ("HG正楷書体-PRO", &["平成明朝"]),
    ("ゴシック", &["MS Gothic"]),
    ("MS Gothic", &["ＭＳ Ｐゴシック"]),
    ("ＭＳ Ｐゴシック", &["MS Gothic"]),
    ("MS Gothic", &["MS UI Gothic"]),
    ("MS UI Gothic", &["平成角ゴシック"]),
    ("平成角ゴシック", &["中ゴシックＢＢＢ"]),
    ("中ゴシックＢＢＢ", &["丸ゴシック−Ｍ"]),
    ("丸ゴシック−Ｍ", &["中ゴシック体"]),
    ("中ゴシック体", &["平成明朝"]),
    ("中ゴシックＢＢＢ−等幅", &["等幅ゴシック"]),
    ("等幅ゴシック", &["中ゴシックＢＢＢ−等幅"]),
    ("WingDings", &["Wingdings"]),
    ("Wingdings", &["MoreWingbats SWM"]),
    ("MT Extra", &["Symbol"]),
    ("수식", &["HyhwpEQ"]),
    ("-윤고딕140", &["한컴 윤고딕 230", "한컴 윤고딕 720", "함초롬돋움", "한컴돋움"]),
    ("-윤고딕150", &["한컴 윤고딕 240", "한컴 윤고딕 740", "함초롬돋움", "한컴돋움"]),
    ("-윤명조120", &["함초롬바탕", "한컴바탕"]),
    ("-윤명조150", &["함초롬바탕", "한컴바탕"]),
    ("-웹윤명조120", &["함초롬바탕", "한컴바탕"]),
    ("KoPubWorld돋움체 Light", &["함초롬돋움", "한컴돋움"]),
    ("KoPubWorld돋움체 Medium", &["함초롬돋움", "한컴돋움"]),
    ("KoPubWorld바탕체 Light", &["함초롬바탕", "한컴바탕"]),
    ("SM3태고딕", &["함초롬돋움", "한컴돋움"]),
    ("SM3신중고딕 01", &["함초롬돋움", "한컴돋움"]),
    ("YDVYMjO13", &["함초롬바탕", "한컴바탕"]),
    ("HCI Acacia", &["함초롬바탕", "한컴바탕"]),
    ("산세리프", &["함초롬돋움", "한컴돋움"]),
    ("바탕", &["한컴바탕", "함초롬바탕"]),
    ("TimesNewRomanPSMT", &["함초롬바탕", "한컴바탕"]),
    ("맑은 고딕", &["함초롬돋움", "한컴돋움"]),
    ("한양신명조", &["함초롬바탕", "한컴바탕"]),
];

pub(crate) const MAP_FONT_CLASS: &[(&str, &[&str])] = &[
    ("Times New Roman", &["TIMES"]),
    ("Times", &["TIMES"]),
    ("Lucida Bright", &["TIMES"]),
    ("Times Roman", &["TIMES"]),
    ("Tms Rmn", &["TIMES"]),
    ("New York", &["TIMES"]),
    ("Sylfaen", &["TIMES"]),
    ("Arial", &["ARIAL"]),
    ("Verdana", &["ARIAL"]),
    ("Lucida Sans", &["ARIAL"]),
    ("Microsoft Sans Serif", &["ARIAL"]),
    ("Helvetica", &["ARIAL"]),
    ("Helv", &["ARIAL"]),
    ("Geneva", &["ARIAL"]),
    ("Chicago", &["ARIAL"]),
    ("Estrangelo Edessa", &["ARIAL"]),
    ("Courier New", &["COURIER"]),
    ("Lucida Sans Typewriter", &["COURIER"]),
    ("Monaco", &["COURIER"]),
    ("Pryamoy", &["ARIAL"]),
    ("Pryamoy Prop", &["COURIER"]),
    ("Latinski", &["TIMES"]),
    ("Bastion", &["ARIAL"]),
    ("APC Courier", &["COURIER"]),
    ("Batang", &["BATANG"]),
    ("바탕", &["BATANG"]),
    ("BatangChe", &["BATANG"]),
    ("바탕체", &["BATANG"]),
    ("AppleMyungjo", &["BATANG", "GUNGSUH"]),
    ("Baekmuk Batang", &["BATANG"]),
    ("백묵 바탕", &["BATANG"]),
    ("Myeongjo", &["BATANG"]),
    ("Gulim", &["GULIM"]),
    ("굴림", &["GULIM"]),
    ("GulimChe", &["GULIM"]),
    ("굴림체", &["GULIM"]),
    ("AppleGothic", &["GULIM", "DOTUM"]),
    ("Baekmuk Gulim", &["GULIM"]),
    ("백묵 굴림", &["GULIM"]),
    ("RoundedGothic", &["GULIM"]),
    ("Dotum", &["DOTUM"]),
    ("돋움", &["DOTUM"]),
    ("DotumChe", &["DOTUM"]),
    ("돋움체", &["DOTUM"]),
    ("Baekmuk Dotum", &["DOTUM"]),
    ("백묵 돋움", &["DOTUM"]),
    ("Gothic", &["DOTUM"]),
    ("Gungsuh", &["GUNGSUH"]),
    ("궁서", &["GUNGSUH"]),
    ("GungsuhChe", &["GUNGSUH"]),
    ("궁서체", &["GUNGSUH"]),
    ("Haeseo", &["GUNGSUH"]),
    ("HY견고딕", &["GULIM"]),
    ("HY견명조", &["BATANG"]),
    ("HY궁서", &["GUNGSUH"]),
    ("HY궁서B", &["GUNGSUH"]),
    ("HY그래픽", &["GULIM"]),
    ("HY그래픽M", &["GULIM"]),
    ("HY둥근고딕", &["GULIM"]),
    ("HY신명조", &["BATANG"]),
    ("HY중고딕", &["GULIM"]),
    ("가는공한", &["BATANG"]),
    ("가는안상수체", &["BATANG"]),
    ("가는한", &["BATANG"]),
    ("가지", &["BATANG"]),
    ("강낭콩", &["BATANG"]),
    ("견고딕", &["DOTUM"]),
    ("견명조", &["BATANG"]),
    ("고딕", &["BATANG"]),
    ("굵은공한", &["BATANG"]),
    ("굵은안상수체", &["BATANG"]),
    ("굵은한", &["BATANG"]),
    ("그래픽", &["GULIM"]),
    ("딸기", &["BATANG"]),
    ("명조", &["BATANG"]),
    ("복숭아", &["BATANG"]),
    ("새굴림", &["GULIM"]),
    ("샘물", &["BATANG"]),
    ("시스템", &["BATANG"]),
    ("시스템 간자", &["BATANG"]),
    ("시스템 약자", &["BATANG"]),
    ("신명조", &["BATANG"]),
    ("신명조 간자", &["BATANG"]),
    ("신명조 약자", &["BATANG"]),
    ("신명조V", &["BATANG"]),
    ("중고딕V", &["DOTUM"]),
    ("양재깨비체B", &["BATANG"]),
    ("Yj GABI Bold", &["BATANG"]),
    ("양재꽃게체M", &["BATANG"]),
    ("Yj GOTGAE Medium", &["BATANG"]),
    ("양재난초체M", &["BATANG"]),
    ("Yj NANCHO Medium", &["BATANG"]),
    ("양재다운명조M", &["BATANG"]),
    ("Yj DWMMOOGJO Medium", &["BATANG"]),
    ("양재둘기체M", &["BATANG"]),
    ("Yj DOOLGI Medium", &["BATANG"]),
    ("양재매화체S", &["BATANG"]),
    ("Yj MAEHWA SemiBold", &["BATANG"]),
    ("양재백두체B", &["BATANG"]),
    ("Yj BACDOO Bold", &["BATANG"]),
    ("양재벨라체M", &["BATANG"]),
    ("YJ BELLA Medium", &["BATANG"]),
    ("양재본목각체M", &["BATANG"]),
    ("Yj BONMOKGAK Medium", &["BATANG"]),
    ("양재붓꽃체L", &["BATANG"]),
    ("Yj BUTGOT Light", &["BATANG"]),
    ("양재블럭체", &["BATANG"]),
    ("Yj BLOCK Medium", &["BATANG"]),
    ("양재샤넬체M", &["BATANG"]),
    ("Yj SHANALL Medium", &["BATANG"]),
    ("양재소슬체S", &["BATANG"]),
    ("Yj SOSEL SemiBold", &["BATANG"]),
    ("양재와당체M", &["BATANG"]),
    ("Yj WADAG Medium", &["BATANG"]),
    ("양재이니셜체", &["BATANG"]),
    ("Yj INITIALPOSITIVE Medium", &["BATANG"]),
    ("양재인장체M", &["BATANG"]),
    ("Yj INJANG Medium", &["BATANG"]),
    ("양재참숯체B", &["BATANG"]),
    ("Yj CHMSOOT Bold", &["BATANG"]),
    ("양재튼튼체B", &["BATANG"]),
    ("Yj TEUNTEUM Bold", &["BATANG"]),
    ("오이", &["BATANG"]),
    ("옥수수", &["BATANG"]),
    ("중간공한", &["BATANG"]),
    ("중간안상수체", &["BATANG"]),
    ("중간한", &["BATANG"]),
    ("중고딕", &["DOTUM"]),
    ("중고딕 간자", &["DOTUM"]),
    ("중고딕 약자", &["DOTUM"]),
    ("타이프", &["BATANG"]),
    ("태 나무", &["BATANG"]),
    ("펜흘림", &["BATANG"]),
    ("필기", &["BATANG"]),
    ("한양해서", &["GUNGSUH"]),
    ("한컴돋움", &["DOTUM"]),
    ("Haansoft Dotum", &["DOTUM"]),
    ("한컴바탕", &["BATANG"]),
    ("Haansoft Batang", &["BATANG"]),
    ("함초롬돋움", &["DOTUM"]),
    ("HCR Dotum", &["DOTUM"]),
    ("함초롬바탕", &["BATANG"]),
    ("한컴 고딕", &["DOTUM"]),
    ("Hancom Gothic", &["DOTUM"]),
    ("Hancom Santteut Dotum", &["DOTUM"]),
    ("한컴산뜻돋움", &["DOTUM"]),
    ("HCR Batang", &["BATANG"]),
    ("한컴 바겐세일 B", &["DOTUM"]),
    ("Haan Sale B", &["DOTUM"]),
    ("한컴 바겐세일 M", &["DOTUM"]),
    ("Haan Sale M", &["DOTUM"]),
    ("한컴 백제 B", &["DOTUM"]),
    ("Haan Baekje B", &["DOTUM"]),
    ("한컴 백제 M", &["DOTUM"]),
    ("Haan Baekje M", &["DOTUM"]),
    ("한컴 소망 B", &["BATANG"]),
    ("Haan Somang B", &["BATANG"]),
    ("한컴 소망 M", &["BATANG"]),
    ("Haan Somang M", &["BATANG"]),
    ("한컴 솔잎 B", &["BATANG"]),
    ("Haan Sollip B", &["BATANG"]),
    ("한컴 솔잎 M", &["BATANG"]),
    ("Haan Sollip M", &["BATANG"]),
    ("한컴 윤고딕 230", &["DOTUM"]),
    ("Haan YGodic 230", &["DOTUM"]),
    ("한컴 윤고딕 240", &["DOTUM"]),
    ("Haan YGodic 240", &["DOTUM"]),
    ("한컴 윤고딕 250", &["DOTUM"]),
    ("Haan YGodic 250", &["DOTUM"]),
    ("한컴 윤체 B", &["HEADLINE"]),
    ("Haan YHead B", &["HEADLINE"]),
    ("한컴 윤체 L", &["HEADLINE"]),
    ("Haan YHead L", &["HEADLINE"]),
    ("한컴 윤체 M", &["HEADLINE"]),
    ("Haan YHead M", &["HEADLINE"]),
    ("한컴 쿨재즈 B", &["BATANG"]),
    ("Haan Cooljazz B", &["BATANG"]),
    ("한컴 쿨재즈 L", &["BATANG"]),
    ("Haan Cooljazz L", &["BATANG"]),
    ("한컴 쿨재즈 M", &["BATANG"]),
    ("Haan Cooljazz M", &["BATANG"]),
    ("맑은 고딕", &["DOTUM"]),
    ("해서 간자", &["BATANG"]),
    ("해서 약자", &["BATANG"]),
    ("HY헤드라인M", &["HEADLINE"]),
    ("HYHeadLine-Medium", &["HEADLINE"]),
    ("HY헤드라인B", &["HEADLINE"]),
    ("HYHeadLine-Bold", &["HEADLINE"]),
    ("헤드라인", &["HEADLINE"]),
    ("헤드라인D", &["HEADLINE"]),
    ("가는헤드라인", &["HEADLINE"]),
    ("가는헤드라인D", &["HEADLINE"]),
    ("휴먼가는샘체", &["BATANG"]),
    ("휴먼가는팸체", &["BATANG"]),
    ("휴먼고딕", &["DOTUM"]),
    ("휴먼굵은샘체", &["BATANG"]),
    ("휴먼굵은팸체", &["BATANG"]),
    ("휴먼명조", &["GULIM"]),
    ("휴먼옛체", &["GUNGSUH"]),
    ("휴먼중간샘체", &["BATANG"]),
    ("휴먼중간팸체", &["BATANG"]),
    ("휴먼둥근헤드라인", &["HEADLINE"]),
    ("한양신명조", &["BATANG"]),
    ("한양견명조", &["BATANG"]),
    ("한양중고딕", &["DOTUM"]),
    ("한양견고딕", &["DOTUM"]),
    ("한양그래픽", &["DOTUM"]),
    ("한양궁서", &["GUNGSUH"]),
    ("한양신명조V", &["BATANG"]),
    ("한양중고딕V", &["DOTUM"]),
    ("가는안상수체영문", &["TIMES"]),
    ("중간안상수체영문", &["TIMES"]),
    ("굵은안상수체영문", &["TIMES"]),
    ("HCI 가는안체영문", &["TIMES"]),
    ("HCI 중간안체영문", &["TIMES"]),
    ("HCI 굵은안체영문", &["TIMES"]),
    ("윤고딕220", &["GULIM"]),
    ("MS Mincho", &["MINCHO"]),
    ("ＭＳ 明朝", &["MINCHO"]),
    ("MS PMincho", &["MINCHO"]),
    ("ＭＳ Ｐ明朝", &["MINCHO"]),
    ("Hiragino Mincho Pro W3", &["MINCHO"]),
    ("Kochi Mincho", &["MINCHO"]),
    ("東風明朝", &["MINCHO"]),
    ("MS PGothic", &["GOTHIC"]),
    ("ＭＳ Ｐゴシック", &["GOTHIC"]),
    ("Osaka", &["GOTHIC"]),
    ("Kochi Gothic", &["GOTHIC"]),
    ("東風ゴシック", &["GOTHIC"]),
    ("SimSun", &["SIMSUN"]),
    ("宋体", &["SIMSUN"]),
    ("Hei", &["SIMSUN"]),
    ("ZYSong18030", &["SIMSUN"]),
    ("中易宋体18030", &["SIMSUN"]),
    ("AR PL SungtiL GB", &["SIMSUN"]),
    ("文鼎ＰＬ简报宋", &["SIMSUN"]),
    ("NSimSun", &["SIMSUN"]),
    ("PMingLiU", &["MINGLIU"]),
    ("超研澤古印體", &["MINGLIU"]),
    ("新細明體", &["MINGLIU"]),
    ("MingLiU", &["MINGLIU"]),
    ("細明體", &["MINGLIU"]),
    ("DFKai-SB", &["MINGLIU"]),
    ("標楷體", &["MINGLIU"]),
    ("Apple LiGothic", &["MINGLIU"]),
    ("AR PL Mingti2L Big5", &["MINGLIU"]),
    ("文鼎ＰＬ細上海宋", &["MINGLIU"]),
];
