// Generated from hftinfo.dat Family Category sections. Do not edit by hand.
use crate::script::Script;

pub(crate) const FACE_TO_FCAT: &[(Script, &str, &str)] = &[
    (Script::Hangul, "명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "샘물", "FCAT_NONRECTGT"),
    (Script::Hangul, "필기", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "시스템", "FCAT_GOTHIC"),
    (Script::Hangul, "HY둥근고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "옛한글", "FCAT_MYUNGJO"),
    (Script::Hangul, "가는공한", "FCAT_MYUNGJO"),
    (Script::Hangul, "중간공한", "FCAT_MYUNGJO"),
    (Script::Hangul, "굵은공한", "FCAT_MYUNGJO"),
    (Script::Hangul, "가는한", "FCAT_GOTHIC"),
    (Script::Hangul, "중간한", "FCAT_GOTHIC"),
    (Script::Hangul, "굵은한", "FCAT_GOTHIC"),
    (Script::Hangul, "휴먼명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "휴먼고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "가는안상수체", "FCAT_NONRECTGT"),
    (Script::Hangul, "중간안상수체", "FCAT_NONRECTGT"),
    (Script::Hangul, "굵은안상수체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼가는샘체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼중간샘체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼굵은샘체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼가는팸체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼중간팸체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼굵은팸체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼옛체", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "한양견명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "한양중고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "한양견고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "한양그래픽", "FCAT_SSERIF"),
    (Script::Hangul, "한양궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "문화바탕", "FCAT_MYUNGJO"),
    (Script::Hangul, "문화바탕제목", "FCAT_MYUNGJO"),
    (Script::Hangul, "문화돋움", "FCAT_GOTHIC"),
    (Script::Hangul, "문화돋움제목", "FCAT_GOTHIC"),
    (Script::Hangul, "문화쓰기", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "문화쓰기흘림", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "펜흘림", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "복숭아", "FCAT_MYUNGJO"),
    (Script::Hangul, "옥수수", "FCAT_MYUNGJO"),
    (Script::Hangul, "오이", "FCAT_MYUNGJO"),
    (Script::Hangul, "가지", "FCAT_MYUNGJO"),
    (Script::Hangul, "강낭콩", "FCAT_MYUNGJO"),
    (Script::Hangul, "딸기", "FCAT_MYUNGJO"),
    (Script::Hangul, "타이프", "FCAT_MYUNGJO"),
    (Script::Hangul, "태 나무", "FCAT_MYUNGJO"),
    (Script::Hangul, "태 헤드라인D", "FCAT_SSERIF"),
    (Script::Hangul, "태 가는 헤드라인D", "FCAT_SSERIF"),
    (Script::Hangul, "태 헤드라인T", "FCAT_SSERIF"),
    (Script::Hangul, "태 가는 헤드라인T", "FCAT_SSERIF"),
    (Script::Hangul, "양재 다운명조M", "FCAT_MYUNGJO"),
    (Script::Hangul, "양재 본목각M", "FCAT_MYUNGJO"),
    (Script::Hangul, "양재 소슬", "FCAT_MYUNGJO"),
    (Script::Hangul, "양재 튼튼B", "FCAT_MYUNGJO"),
    (Script::Hangul, "양재 참숯B", "FCAT_GOTHIC"),
    (Script::Hangul, "양재 둘기", "FCAT_GOTHIC"),
    (Script::Hangul, "양재 매화", "FCAT_GOTHIC"),
    (Script::Hangul, "양재 샤넬", "FCAT_GOTHIC"),
    (Script::Hangul, "양재 와당", "FCAT_GOTHIC"),
    (Script::Hangul, "양재 이니셜", "FCAT_GOTHIC"),
    (Script::Hangul, "신명 세명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 신명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 신신명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 중명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 태명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 견명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 신문명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 순명조", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 세고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "신명 중고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "신명 태고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "신명 견고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "신명 세나루", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 디나루", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 신그래픽", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 태그래픽", "FCAT_MYUNGJO"),
    (Script::Hangul, "신명 궁서", "FCAT_MYUNGJO"),
    (Script::Hangul, "#세명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#신명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#중명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#신중명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#화명조A", "FCAT_GOTHIC"),
    (Script::Hangul, "#화명조B", "FCAT_GOTHIC"),
    (Script::Hangul, "#태명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#신태명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#태신명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#견명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문명조", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문태명", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문견명", "FCAT_GOTHIC"),
    (Script::Hangul, "#세고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#신세고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#중고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#태고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#견고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문고딕", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문태고", "FCAT_GOTHIC"),
    (Script::Hangul, "#신문견고", "FCAT_GOTHIC"),
    (Script::Hangul, "#세나루", "FCAT_GOTHIC"),
    (Script::Hangul, "#신세나루", "FCAT_GOTHIC"),
    (Script::Hangul, "#디나루", "FCAT_GOTHIC"),
    (Script::Hangul, "#신디나루", "FCAT_GOTHIC"),
    (Script::Hangul, "#그래픽", "FCAT_GOTHIC"),
    (Script::Hangul, "#신그래픽", "FCAT_GOTHIC"),
    (Script::Hangul, "#태그래픽", "FCAT_GOTHIC"),
    (Script::Hangul, "#궁서", "FCAT_GOTHIC"),
    (Script::Hangul, "#공작", "FCAT_GOTHIC"),
    (Script::Hangul, "#수암A", "FCAT_GOTHIC"),
    (Script::Hangul, "#수암B", "FCAT_GOTHIC"),
    (Script::Hangul, "#빅", "FCAT_GOTHIC"),
    (Script::Hangul, "산돌 독수리 Bold", "FCAT_MYUNGJO"),
    (Script::Hangul, "산돌 둥근장식 Bold", "FCAT_MYUNGJO"),
    (Script::Hangul, "산돌 상아 Bold", "FCAT_MYUNGJO"),
    (Script::Hangul, "산돌 숲 Light", "FCAT_MYUNGJO"),
    (Script::Hangul, "산돌 스케치 Light", "FCAT_MYUNGJO"),
    (Script::Hangul, "산돌 예일 Light", "FCAT_MYUNGJO"),
    (Script::Hangul, "태 물방울-R", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "태 바람D-B", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "태 사다리-B", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "태 으뜸-L", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "태 조각V-B", "FCAT_GOTHIC"),
    (Script::Hangul, "태 흘림체-L", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "가는샘물", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "가는샘물세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "가로무늬헤드", "FCAT_GOTHIC"),
    (Script::Hangul, "가로수", "FCAT_MYUNGJO"),
    (Script::Hangul, "각헤드", "FCAT_GOTHIC"),
    (Script::Hangul, "강철", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "강철세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "곧은체", "FCAT_MYUNGJO"),
    (Script::Hangul, "교회", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "굵은샘물", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "굵은샘물세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "궁서1", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "궁서1세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "궁행서", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "궁행서세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "그래픽1", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "그래픽1세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "그림", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "긴고딕", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "긴고딕세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "김치", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "낙서", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "둥근안상수", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "둥근안상수세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "디나루", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "디나루세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "디자인", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "류강", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "류강세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "명조2", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "명조2세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "모란", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "모란세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "문헤드", "FCAT_GOTHIC"),
    (Script::Hangul, "바다", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "바이트", "FCAT_MYUNGJO"),
    (Script::Hangul, "베틀", "FCAT_GOTHIC"),
    (Script::Hangul, "본문", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "본문세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "붓글씨", "FCAT_MYUNGJO"),
    (Script::Hangul, "빗살무늬", "FCAT_GOTHIC"),
    (Script::Hangul, "빠꼼", "FCAT_GOTHIC"),
    (Script::Hangul, "사각", "FCAT_GOTHIC"),
    (Script::Hangul, "샘물고딕", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "샘물고딕세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "샘물인포", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "샘물인포세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "세나루", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "세나루세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "세로무늬헤드", "FCAT_GOTHIC"),
    (Script::Hangul, "세로영화체", "FCAT_GOTHIC"),
    (Script::Hangul, "소라", "FCAT_MYUNGJO"),
    (Script::Hangul, "소망", "FCAT_MYUNGJO"),
    (Script::Hangul, "손글예쁜", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "손글이쁜", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송각진필기", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송경아", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송경아-O", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송고딕", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송샘", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "송샘물필기", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "수줍음", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "신선", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "신선명조", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "신선명조세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "실팸", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "실팸세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "안샘", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "안샘세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "어린이", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "영화체", "FCAT_GOTHIC"),
    (Script::Hangul, "옛고딕", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "옛고딕세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "용수철고딕", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "용수철고딕세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "원주", "FCAT_GOTHIC"),
    (Script::Hangul, "인영", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "인포", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "전서", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "전서세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "쥐파먹은헤드", "FCAT_GOTHIC"),
    (Script::Hangul, "직선체", "FCAT_MYUNGJO"),
    (Script::Hangul, "찬현", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "청개구리", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "청개구리세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "큰머리", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "큰머리세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "키다리", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "키다리세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "파도", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "파도세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "한궁", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "한궁세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "한메샘물", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "혜성", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "훈민정음", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "휴먼궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "휴먼둥근고딕", "FCAT_SSERIF"),
    (Script::Hangul, "휴먼둥근헤드라인", "FCAT_SSERIF"),
    (Script::Hangul, "휴먼매직체", "FCAT_NONRECTGT"),
    (Script::Hangul, "휴먼세엑스포", "FCAT_GOTHIC"),
    (Script::Hangul, "휴먼소하체", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "휴먼엑스포", "FCAT_GOTHIC"),
    (Script::Hangul, "휴먼편지체", "FCAT_NONRECTGT"),
    (Script::Hangul, "흘림", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "흘림세로", "FCAT_BRUSHSCRIPT"),
    (Script::Hangul, "희망", "FCAT_MYUNGJO"),
    (Script::Latin, "명조", "FCAT_MYUNGJO"),
    (Script::Latin, "고딕", "FCAT_GOTHIC"),
    (Script::Latin, "산세리프", "FCAT_GOTHIC"),
    (Script::Latin, "필기", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Latin, "한양중고딕", "FCAT_GOTHIC"),
    (Script::Latin, "시스템", "FCAT_MYUNGJO"),
    (Script::Latin, "HY둥근고딕", "FCAT_GOTHIC"),
    (Script::Latin, "가는공한", "FCAT_MYUNGJO"),
    (Script::Latin, "중간공한", "FCAT_MYUNGJO"),
    (Script::Latin, "굵은공한", "FCAT_MYUNGJO"),
    (Script::Latin, "가는한", "FCAT_GOTHIC"),
    (Script::Latin, "중간한", "FCAT_GOTHIC"),
    (Script::Latin, "굵은한", "FCAT_GOTHIC"),
    (Script::Latin, "한양견명조", "FCAT_MYUNGJO"),
    (Script::Latin, "한양견고딕", "FCAT_GOTHIC"),
    (Script::Latin, "한양그래픽", "FCAT_SSERIF"),
    (Script::Latin, "한양궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "HCI Tulip", "FCAT_MYUNGJO"),
    (Script::Latin, "HCI Hollyhock", "FCAT_GOTHIC"),
    (Script::Latin, "HCI Columbine", "FCAT_GOTHIC"),
    (Script::Latin, "HCI Acacia", "FCAT_GOTHIC"),
    (Script::Latin, "HCI Bellflower", "FCAT_MYUNGJO"),
    (Script::Latin, "HCI Hollyhock Narrow", "FCAT_GOTHIC"),
    (Script::Latin, "HCI Morning Glory", "FCAT_MYUNGJO"),
    (Script::Latin, "HCI Poppy", "FCAT_MYUNGJO"),
    (Script::Latin, "HCI Centaurea", "FCAT_MYUNGJO"),
    (Script::Latin, "가는안상수체영문", "FCAT_SSERIF"),
    (Script::Latin, "중간안상수체영문", "FCAT_SSERIF"),
    (Script::Latin, "굵은안상수체영문", "FCAT_SSERIF"),
    (Script::Latin, "펜흘림", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "옥수수", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "오이", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "타이프", "FCAT_MYUNGJO"),
    (Script::Latin, "태 나무", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "양재 다운명조M", "FCAT_MYUNGJO"),
    (Script::Latin, "양재 본목각M", "FCAT_MYUNGJO"),
    (Script::Latin, "양재 소슬", "FCAT_MYUNGJO"),
    (Script::Latin, "양재 튼튼B", "FCAT_MYUNGJO"),
    (Script::Latin, "양재 참숯B", "FCAT_GOTHIC"),
    (Script::Latin, "양재 둘기", "FCAT_GOTHIC"),
    (Script::Latin, "양재 매화", "FCAT_GOTHIC"),
    (Script::Latin, "양재 샤넬", "FCAT_GOTHIC"),
    (Script::Latin, "양재 와당", "FCAT_GOTHIC"),
    (Script::Latin, "양재 이니셜", "FCAT_GOTHIC"),
    (Script::Latin, "수식", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 세명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 신명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 신신명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 중명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 태명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 견명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 신문명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 순명조", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 세고딕", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 중고딕", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 태고딕", "FCAT_GOTHIC"),
    (Script::Latin, "신명 견고딕", "FCAT_GOTHIC"),
    (Script::Latin, "신명 신문고딕", "FCAT_GOTHIC"),
    (Script::Latin, "신명 세나루", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 디나루", "FCAT_SSERIF"),
    (Script::Latin, "신명 신그래픽", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 태그래픽", "FCAT_MYUNGJO"),
    (Script::Latin, "신명 궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "#세명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#신명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#중명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#신중명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#화명조A", "FCAT_MYUNGJO"),
    (Script::Latin, "#화명조B", "FCAT_MYUNGJO"),
    (Script::Latin, "#태명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#신태명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#태신명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#견명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#신문명조", "FCAT_MYUNGJO"),
    (Script::Latin, "#신문태명", "FCAT_MYUNGJO"),
    (Script::Latin, "#신문견명", "FCAT_MYUNGJO"),
    (Script::Latin, "#세고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#신세고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#중고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#태고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#견고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#신문고딕", "FCAT_GOTHIC"),
    (Script::Latin, "#신문태고", "FCAT_GOTHIC"),
    (Script::Latin, "#신문견고", "FCAT_GOTHIC"),
    (Script::Latin, "#세나루", "FCAT_SSERIF"),
    (Script::Latin, "#신세나루", "FCAT_SSERIF"),
    (Script::Latin, "#디나루", "FCAT_SSERIF"),
    (Script::Latin, "#신디나루", "FCAT_SSERIF"),
    (Script::Latin, "#그래픽", "FCAT_GOTHIC"),
    (Script::Latin, "#신그래픽", "FCAT_GOTHIC"),
    (Script::Latin, "#태그래픽", "FCAT_SSERIF"),
    (Script::Latin, "#궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "#필기", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "#공작", "FCAT_GOTHIC"),
    (Script::Latin, "#수암A", "FCAT_GOTHIC"),
    (Script::Latin, "#수암B", "FCAT_GOTHIC"),
    (Script::Latin, "#헤드라인A", "FCAT_GOTHIC"),
    (Script::Latin, "#헤드라인B", "FCAT_GOTHIC"),
    (Script::Latin, "#빅", "FCAT_GOTHIC"),
    (Script::Latin, "AmeriGarmnd BT", "FCAT_MYUNGJO"),
    (Script::Latin, "Baskerville BT", "FCAT_MYUNGJO"),
    (Script::Latin, "Bodoni Bd BT", "FCAT_MYUNGJO"),
    (Script::Latin, "Bodoni Bk BT", "FCAT_MYUNGJO"),
    (Script::Latin, "CentSchbook BT", "FCAT_MYUNGJO"),
    (Script::Latin, "Courier10 BT", "FCAT_GOTHIC"),
    (Script::Latin, "GoudyOlSt BT", "FCAT_MYUNGJO"),
    (Script::Latin, "OCR-A BT", "FCAT_GOTHIC"),
    (Script::Latin, "OCR-B-10 BT", "FCAT_GOTHIC"),
    (Script::Latin, "Orator10 BT", "FCAT_GOTHIC"),
    (Script::Latin, "Swis721 Lt BT", "FCAT_SSERIF"),
    (Script::Latin, "BernhardFashion BT", "FCAT_SSERIF"),
    (Script::Latin, "Blippo Blk BT", "FCAT_SSERIF"),
    (Script::Latin, "BroadwayEngraved BT", "FCAT_SSERIF"),
    (Script::Latin, "BrushScript BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "Cooper Blk BT", "FCAT_MYUNGJO"),
    (Script::Latin, "CommercialScript BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "DomCasual BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "Freehand591 BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "FuturaBlack BT", "FCAT_GOTHIC"),
    (Script::Latin, "Hobo BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "Liberty BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "MurrayHill Bd BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "Newtext Bk BT", "FCAT_MYUNGJO"),
    (Script::Latin, "Orbit-B BT", "FCAT_GOTHIC"),
    (Script::Latin, "ParkAvenue BT", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "Stencil BT", "FCAT_MYUNGJO"),
    (Script::Latin, "산돌 독수리 Bold", "FCAT_SSERIF"),
    (Script::Latin, "산돌 둥근장식 Bold", "FCAT_MYUNGJO"),
    (Script::Latin, "산돌 상아 Bold", "FCAT_SSERIF"),
    (Script::Latin, "산돌 숲 Light", "FCAT_SSERIF"),
    (Script::Latin, "산돌 스케치 Light", "FCAT_MYUNGJO"),
    (Script::Latin, "산돌 예일 Light", "FCAT_SSERIF"),
    (Script::Latin, "태 굵은고딕", "FCAT_GOTHIC"),
    (Script::Latin, "태 물방울-R", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "태 으뜸-L", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "태 흘림체-L", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "깜장", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "송필", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "오퍼스", "FCAT_BRUSHSCRIPT"),
    (Script::Latin, "이야기", "FCAT_BRUSHSCRIPT"),
    (Script::Hanja, "명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "한양중고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "시스템", "FCAT_GOTHIC"),
    (Script::Hanja, "신명조 약자", "FCAT_MYUNGJO"),
    (Script::Hanja, "중고딕 약자", "FCAT_GOTHIC"),
    (Script::Hanja, "해서 약자", "FCAT_MYUNGJO"),
    (Script::Hanja, "시스템 약자", "FCAT_GOTHIC"),
    (Script::Hanja, "신명조 간자", "FCAT_MYUNGJO"),
    (Script::Hanja, "중고딕 간자", "FCAT_GOTHIC"),
    (Script::Hanja, "해서 간자", "FCAT_MYUNGJO"),
    (Script::Hanja, "시스템 간자", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 세명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 중명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 태명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 견명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 신문명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "신명 세고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "신명 중고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "신명 태고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "신명 견고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "신명 궁서", "FCAT_MYUNGJO"),
    (Script::Hanja, "#신명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "#중명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "#태명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "#견명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "#신문명조", "FCAT_MYUNGJO"),
    (Script::Hanja, "#신문견명", "FCAT_MYUNGJO"),
    (Script::Hanja, "#신세고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "#중고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "#태고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "#견고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "#신문고딕", "FCAT_GOTHIC"),
    (Script::Hanja, "#신문견고", "FCAT_GOTHIC"),
    (Script::Hanja, "#신세나루", "FCAT_GOTHIC"),
    (Script::Hanja, "#신디나루", "FCAT_GOTHIC"),
    (Script::Hanja, "#궁서", "FCAT_MYUNGJO"),
    (Script::Japanese, "명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "한양중고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "시스템", "FCAT_GOTHIC"),
    (Script::Japanese, "HY둥근고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "신명 신명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 태명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 견명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 중고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "신명 태고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "#세명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "#태명조", "FCAT_MYUNGJO"),
    (Script::Japanese, "#세고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "#중고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "#태고딕", "FCAT_GOTHIC"),
    (Script::Japanese, "한양신명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "한양중고딕V", "FCAT_GOTHIC"),
    (Script::Japanese, "신명 신명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 태명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 견명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "신명 중고딕V", "FCAT_GOTHIC"),
    (Script::Japanese, "신명 태고딕V", "FCAT_GOTHIC"),
    (Script::Japanese, "#세명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "#태명조V", "FCAT_MYUNGJO"),
    (Script::Japanese, "#세고딕V", "FCAT_GOTHIC"),
    (Script::Japanese, "#중고딕V", "FCAT_GOTHIC"),
    (Script::Japanese, "#태고딕V", "FCAT_GOTHIC"),
    (Script::Other, "명조", "FCAT_MYUNGJO"),
    (Script::Other, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Other, "수식", "FCAT_MYUNGJO"),
    (Script::Symbol, "명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "시스템", "FCAT_GOTHIC"),
    (Script::Symbol, "HY둥근고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "한양신명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "한양중고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "수식", "FCAT_MYUNGJO"),
    (Script::Symbol, "신명 견명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "신명 견고딕", "FCAT_MYUNGJO"),
    (Script::Symbol, "신명 태그래픽", "FCAT_MYUNGJO"),
    (Script::Symbol, "#세명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#신명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#중명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#태명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#신태명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#태신명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#견명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#신문명조", "FCAT_MYUNGJO"),
    (Script::Symbol, "#세고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#신세고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#중고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#태고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#견고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#신문고딕", "FCAT_GOTHIC"),
    (Script::Symbol, "#세나루", "FCAT_SSERIF"),
    (Script::Symbol, "#신세나루", "FCAT_SSERIF"),
    (Script::Symbol, "#디나루", "FCAT_SSERIF"),
    (Script::Symbol, "#신디나루", "FCAT_SSERIF"),
    (Script::Symbol, "#그래픽", "FCAT_GOTHIC"),
    (Script::Symbol, "#신그래픽", "FCAT_GOTHIC"),
    (Script::Symbol, "#태그래픽", "FCAT_GOTHIC"),
    (Script::Symbol, "#궁서", "FCAT_BRUSHSCRIPT"),
    (Script::Symbol, "#필기", "FCAT_BRUSHSCRIPT"),
    (Script::Symbol, "#공작", "FCAT_GOTHIC"),
    (Script::Symbol, "#수암A", "FCAT_GOTHIC"),
    (Script::Symbol, "#빅", "FCAT_GOTHIC"),
    (Script::User, "명조", "FCAT_MYUNGJO"),
    (Script::User, "한글 풀어쓰기", "FCAT_MYUNGJO"),
    (Script::User, "산돌 ClipArt", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 사인 1", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 사인 2", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 사인 3", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 사인 4", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 패턴", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 픽토그램 1", "FCAT_BRUSHSCRIPT"),
    (Script::User, "산돌 픽토그램 2", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(곤충)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(동물)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(사람)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(사물)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(식물)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(어류)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(조류)", "FCAT_BRUSHSCRIPT"),
    (Script::User, "수려아트(종교)", "FCAT_BRUSHSCRIPT"),
];

pub(crate) const FCAT_TO_FAMILY: &[(Script, &str, &str)] = &[
    (Script::Hangul, "FCAT_MYUNGJO", "Batang"),
    (Script::Hangul, "FCAT_GOTHIC", "Dotum"),
    (Script::Hangul, "FCAT_SSERIF", "Gulim"),
    (Script::Hangul, "FCAT_BRUSHSCRIPT", "Gungsuh"),
    (Script::Hangul, "FCAT_DECORATIVE", "Gungsuh"),
    (Script::Hangul, "FCAT_NONRECTMJ", "Batang"),
    (Script::Hangul, "FCAT_NONRECTGT", "Dotum"),
    (Script::Latin, "FCAT_MYUNGJO", "Times New Roman"),
    (Script::Latin, "FCAT_GOTHIC", "Arial"),
    (Script::Latin, "FCAT_SSERIF", "Tahoma"),
    (Script::Latin, "FCAT_BRUSHSCRIPT", "Comic Sans MS"),
    (Script::Latin, "FCAT_DECORATIVE", "Comic Sans MS"),
    (Script::Latin, "FCAT_NONRECTMJ", "Times New Roman"),
    (Script::Latin, "FCAT_NONRECTGT", "Arial"),
    (Script::Hanja, "FCAT_MYUNGJO", "Batang"),
    (Script::Hanja, "FCAT_GOTHIC", "Dotum"),
    (Script::Hanja, "FCAT_SSERIF", "Gulim"),
    (Script::Hanja, "FCAT_BRUSHSCRIPT", "Gungsuh"),
    (Script::Hanja, "FCAT_DECORATIVE", "Gungsuh"),
    (Script::Hanja, "FCAT_NONRECTMJ", "Batang"),
    (Script::Hanja, "FCAT_NONRECTGT", "Dotum"),
    (Script::Japanese, "FCAT_MYUNGJO", "Batang"),
    (Script::Japanese, "FCAT_GOTHIC", "Dotum"),
    (Script::Japanese, "FCAT_SSERIF", "Gulim"),
    (Script::Japanese, "FCAT_BRUSHSCRIPT", "Gungsuh"),
    (Script::Japanese, "FCAT_DECORATIVE", "Gungsuh"),
    (Script::Japanese, "FCAT_NONRECTMJ", "Batang"),
    (Script::Japanese, "FCAT_NONRECTGT", "Dotum"),
    (Script::Other, "FCAT_MYUNGJO", "Batang"),
    (Script::Other, "FCAT_GOTHIC", "Dotum"),
    (Script::Other, "FCAT_SSERIF", "Gulim"),
    (Script::Other, "FCAT_BRUSHSCRIPT", "Gungsuh"),
    (Script::Other, "FCAT_DECORATIVE", "Gungsuh"),
    (Script::Other, "FCAT_NONRECTMJ", "Batang"),
    (Script::Other, "FCAT_NONRECTGT", "Dotum"),
    (Script::Symbol, "FCAT_MYUNGJO", "Times New Roman"),
    (Script::Symbol, "FCAT_GOTHIC", "Arial"),
    (Script::Symbol, "FCAT_SSERIF", "Tahoma"),
    (Script::Symbol, "FCAT_BRUSHSCRIPT", "Comic Sans MS"),
    (Script::Symbol, "FCAT_DECORATIVE", "Comic Sans MS"),
    (Script::Symbol, "FCAT_NONRECTMJ", "Times New Roman"),
    (Script::Symbol, "FCAT_NONRECTGT", "Arial"),
    (Script::User, "FCAT_MYUNGJO", "Batang"),
    (Script::User, "FCAT_GOTHIC", "Dotum"),
    (Script::User, "FCAT_SSERIF", "Gulim"),
    (Script::User, "FCAT_BRUSHSCRIPT", "Gungsuh"),
    (Script::User, "FCAT_DECORATIVE", "Gungsuh"),
    (Script::User, "FCAT_NONRECTMJ", "Batang"),
    (Script::User, "FCAT_NONRECTGT", "Dotum"),
];
